package com.example.shoppinglistapp.data.local.entity;

import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.ColumnInfo;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

@Entity(tableName = "category",
        foreignKeys = @ForeignKey(entity = ShoppingList.class, parentColumns = "id", childColumns = "shopping_list_id", onDelete = ForeignKey.CASCADE))
public class Category {
    @PrimaryKey(autoGenerate = true)
    private long id;

    @ColumnInfo(name = "name")
    private String name;

    @ColumnInfo(name = "position", defaultValue = "-1")
    private int position;


    @ColumnInfo(name = "shopping_list_id", index = true)
    private long shoppingListId;

    // No-arg constructor (required by Room)
    public Category() {}

    // Constructor for creating new category
    @Ignore
    public Category(String name, long shoppingListId) {
        this.name = name;
        this.shoppingListId = shoppingListId;
        this.position = -1;
    }

    // Getters and Setters
    public long getId() { return id; }
    public void setId(long id) { this.id = id; }  // Room uses this when loading from DB

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public int getPosition() { return position; }
    public void setPosition(int position) { this.position = position; }

    public long getShoppingListId() { return shoppingListId; }
    public void setShoppingListId(long shoppingListId) { this.shoppingListId = shoppingListId; }

    // copy
    public Category copyForShoppingList(long newShoppingListId) {
        Category copy = new Category();
        copy.setName(this.name);
        copy.setPosition(this.position);
        copy.setShoppingListId(newShoppingListId);
        // id is not set; will be generated by Room
        return copy;
    }

}
