package com.example.shoppinglistapp.data.local.entity;

import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.ColumnInfo;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

@Entity(tableName = "item", foreignKeys = @ForeignKey(entity = Category.class, parentColumns = "id", childColumns = "category_id", onDelete = ForeignKey.CASCADE))
public class Item {
    @PrimaryKey(autoGenerate = true)
    public long id;

    @ColumnInfo(name = "description")
    private String description;

    @ColumnInfo(name = "is_done")
    private boolean isDone;

    @ColumnInfo(name = "position", defaultValue = "-1")
    private int position;


    @ColumnInfo(name = "category_id", index = true)
    private long categoryId;

    // No arg constructor (required by Room)
    public Item() {}


    // Constructor for creating new item
    @Ignore
    public Item(String description, long categoryId) {
        this.description = description;
        this.isDone = false;
        this.categoryId = categoryId;
        this.position = -1;
    }

    // Getters and Setters
    public long getId() { return id; }
    public void setId(long id) { this.id = id; }  // Room uses this when loading from DB

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public boolean isDone() { return isDone; }
    public void setDone(boolean isDone) { this.isDone = isDone; }
    public void reverseChecked() { this.isDone = !this.isDone; }


    public int getPosition() { return position; }
    public void setPosition(int position) { this.position = position; }


    public long getCategoryId() { return categoryId; }
    public void setCategoryId(long categoryId) { this.categoryId = categoryId; }


    // Item.java
    public Item copyForCategory(long newCategoryId) {
        Item copy = new Item();
        copy.setDescription(this.description);
        copy.setDone(false);              // copied items start undone
        copy.setPosition(this.position);
        copy.setCategoryId(newCategoryId);
        // id is not set; will be generated by Room
        return copy;
    }

}
