package com.example.shoppinglistapp.data.local.entity;

import androidx.room.Entity;
import androidx.room.ColumnInfo;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import java.util.Date;

@Entity(tableName = "shopping_list")
public class ShoppingList {
    @PrimaryKey(autoGenerate = true)
    private long id;

    @ColumnInfo(name = "title")
    private String title;

    @ColumnInfo(name = "is_favourite", defaultValue = "0", index = true)
    private boolean isFavourite;

    @ColumnInfo(name = "created_at")
    private Date createdAt;

    // No-arg constructor (required by Room)
    public ShoppingList() {}

    // Convenience constructor for creating new lists
    @Ignore
    public ShoppingList(String title, Date createdAt) {
        this.title = title;
        this.createdAt = createdAt;
        this.isFavourite = false;
        // id is left as 0; Room will assign it when inserted
    }

    // setters and getters...
    public long getId() { return id; }
    public void setId(long id) { this.id = id; }  // Room uses this when loading from DB

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public boolean isFavourite() { return isFavourite; }
    public void setFavourite(boolean isFavourite) { this.isFavourite = isFavourite; }

    public Date getCreatedAt() { return createdAt; }
    public void setCreatedAt(Date createdAt) { this.createdAt = createdAt; }

    // copy
    public ShoppingList copy() {
        ShoppingList copy = new ShoppingList();
        copy.setTitle(this.title);
        copy.setCreatedAt(new Date());   // new creation date
        copy.setFavourite(false);        // copied lists are not favourite
        // id is not set; will be generated by Room
        return copy;
    }
}
